version: '3'
services:
  icap-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-icap-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_icap_api:/usr/lib/python3.6/site-packages/vlab_icap_api
    command: ["python3", "app.py"]

  icap-worker:
    image:
      willnx/vlab-icap-worker
    volumes:
      - ./vlab_icap_api:/usr/lib/python3.6/site-packages/vlab_icap_api
      - /mnt/raid/images/icap:/images:ro
    environment:
      - INF_VCENTER_SERVER=changeME
      - INF_VCENTER_USER=changeME
      - INF_VCENTER_PASSWORD=changeME
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  icap-broker:
    image:
      rabbitmq:3.7-alpine
